from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from io import BytesIO
from pathlib import Path

from backend.schemas import DocumentRequest, DocumentResponse
from backend.services.document_service import generate_legal_document

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from fpdf import FPDF


router = APIRouter()


class ExportRequest(BaseModel):
    content: str


# =========================================================
# GENERATE DOCUMENT
# =========================================================

@router.post("/generate", response_model=DocumentResponse)
def generate_document(request: DocumentRequest):

    try:

        document = generate_legal_document(
            request.document_type,
            request.parties,
            request.terms,
            request.dates
        )

        return DocumentResponse(
            document=document
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc)
        )


# =========================================================
# EXPORT DOCX
# =========================================================

@router.post("/export/docx")
def export_docx(request: ExportRequest):

    try:

        doc = Document()

        # -----------------------------------------------------
        # PAGE SETTINGS
        # -----------------------------------------------------

        section = doc.sections[0]

        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

        # -----------------------------------------------------
        # DEFAULT FONT
        # -----------------------------------------------------

        normal_style = doc.styles["Normal"]

        normal_style.font.name = "Times New Roman"
        normal_style.font.size = Pt(12)

        # -----------------------------------------------------
        # TITLE
        # -----------------------------------------------------

        title = doc.add_paragraph()

        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        title_run = title.add_run(
            "LEGAL DOCUMENT"
        )

        title_run.bold = True
        title_run.font.name = "Times New Roman"
        title_run.font.size = Pt(16)

        title.paragraph_format.space_after = Pt(18)

        # -----------------------------------------------------
        # DOCUMENT CONTENT
        # -----------------------------------------------------

        for line in request.content.split("\n"):

            line = line.strip()

            if not line:
                continue

            paragraph = doc.add_paragraph()

            paragraph.paragraph_format.space_after = Pt(8)
            paragraph.paragraph_format.line_spacing = 1.15

            # Detect headings
            is_heading = (
                line.isupper()
                or line.endswith(":")
                or any(
                    line.startswith(f"{number}.")
                    for number in range(1, 10)
                )
            )

            run = paragraph.add_run(line)

            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

            if is_heading:

                run.bold = True

                paragraph.paragraph_format.space_before = Pt(10)
                paragraph.paragraph_format.space_after = Pt(6)

        # -----------------------------------------------------
        # FOOTER
        # -----------------------------------------------------

        footer = section.footer

        footer_paragraph = footer.paragraphs[0]

        footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        footer_run = footer_paragraph.add_run(
            "Generated by LegalEase"
        )

        footer_run.font.name = "Times New Roman"
        footer_run.font.size = Pt(9)

        # -----------------------------------------------------
        # SAVE DOCX TO MEMORY
        # -----------------------------------------------------

        file_stream = BytesIO()

        doc.save(file_stream)

        file_stream.seek(0)

        return StreamingResponse(
            file_stream,
            media_type=(
                "application/"
                "vnd.openxmlformats-officedocument."
                "wordprocessingml.document"
            ),
            headers={
                "Content-Disposition":
                    "attachment; filename=LegalEase_Document.docx"
            }
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc)
        )


# =========================================================
# PDF CLASS
# =========================================================

class LegalEasePDF(FPDF):

    def __init__(self, font_path):

        super().__init__()

        self.font_path = font_path

        # Add Unicode font
        self.add_font(
            "UnicodeFont",
            "",
            str(font_path),
            uni=True
        )

        # Page configuration
        self.set_auto_page_break(
            auto=True,
            margin=22
        )

    # ---------------------------------------------------------
    # HEADER
    # ---------------------------------------------------------

    def header(self):

        self.set_font(
            "UnicodeFont",
            "",
            9
        )

        self.cell(
            0,
            6,
            "LegalEase",
            ln=True,
            align="L"
        )

        self.line(
            10,
            17,
            200,
            17
        )

        self.ln(5)

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    def footer(self):

        self.set_y(-15)

        self.line(
            10,
            self.get_y(),
            200,
            self.get_y()
        )

        self.set_font(
            "UnicodeFont",
            "",
            8
        )

        self.cell(
            0,
            8,
            f"Generated by LegalEase | Page {self.page_no()}",
            align="C"
        )


# =========================================================
# EXPORT PDF
# =========================================================

@router.post("/export/pdf")
def export_pdf(request: ExportRequest):

    try:

        # -----------------------------------------------------
        # FIND UNICODE FONT
        # -----------------------------------------------------

        font_candidates = [

            Path("C:/Windows/Fonts/arial.ttf"),

            Path("C:/Windows/Fonts/segoeui.ttf"),

            Path("C:/Windows/Fonts/calibri.ttf")

        ]

        font_path = None

        for candidate in font_candidates:

            if candidate.exists():

                font_path = candidate

                break

        if font_path is None:

            raise FileNotFoundError(
                "No Unicode TrueType font was found on this computer."
            )

        # -----------------------------------------------------
        # CREATE PDF
        # -----------------------------------------------------

        pdf = LegalEasePDF(
            font_path
        )

        pdf.add_page()

        # -----------------------------------------------------
        # DOCUMENT TITLE
        # -----------------------------------------------------

        pdf.set_font(
            "UnicodeFont",
            "",
            18
        )

        pdf.cell(
            0,
            12,
            "LEGAL DOCUMENT",
            ln=True,
            align="C"
        )

        pdf.ln(6)

        # -----------------------------------------------------
        # DOCUMENT CONTENT
        # -----------------------------------------------------

        for line in request.content.split("\n"):

            line = line.strip()

            if not line:
                continue

            # -------------------------------------------------
            # HEADING DETECTION
            # -------------------------------------------------

            is_heading = (
                line.isupper()
                or line.endswith(":")
                or any(
                    line.startswith(f"{number}.")
                    for number in range(1, 10)
                )
            )

            # -------------------------------------------------
            # BULLET DETECTION
            # -------------------------------------------------

            is_bullet = (
                line.startswith("- ")
                or line.startswith("* ")
                or line.startswith("• ")
                or line.startswith("(a)")
                or line.startswith("(b)")
                or line.startswith("(c)")
            )

            # -------------------------------------------------
            # HEADINGS
            # -------------------------------------------------

            if is_heading:

                pdf.set_font(
                    "UnicodeFont",
                    "",
                    12
                )

                pdf.multi_cell(
                    0,
                    7,
                    line
                )

                pdf.ln(2)

            # -------------------------------------------------
            # BULLET POINTS
            # -------------------------------------------------

            elif is_bullet:

                pdf.set_font(
                    "UnicodeFont",
                    "",
                    11
                )

                # Convert common bullet formats
                if line.startswith("- "):

                    line = "• " + line[2:]

                elif line.startswith("* "):

                    line = "• " + line[2:]

                pdf.multi_cell(
                    0,
                    7,
                    line
                )

                pdf.ln(1)

            # -------------------------------------------------
            # NORMAL PARAGRAPH
            # -------------------------------------------------

            else:

                pdf.set_font(
                    "UnicodeFont",
                    "",
                    11
                )

                pdf.multi_cell(
                    0,
                    7,
                    line
                )

                pdf.ln(2)

        # -----------------------------------------------------
        # GENERATE PDF BYTES
        # -----------------------------------------------------

        pdf_output = pdf.output(
            dest="S"
        )

        if isinstance(pdf_output, str):

            pdf_output = pdf_output.encode(
                "latin-1"
            )

        file_stream = BytesIO(
            pdf_output
        )

        file_stream.seek(0)

        # -----------------------------------------------------
        # RETURN PDF
        # -----------------------------------------------------

        return StreamingResponse(

            file_stream,

            media_type="application/pdf",

            headers={
                "Content-Disposition":
                    "attachment; filename=LegalEase_Document.pdf"
            }
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc)
        )